#!/bin/sh

# Enable error handling
set -eu

# =============================================================================
# Help Functions
# =============================================================================
# -----------------------------------------------------------------------------
# Display help information (general or command-specific)
# -----------------------------------------------------------------------------
show_help() {
    target="${1:-}"

    case "$target" in
        "version")
            echo "cccp.sh version - Predictive Semantic Versioning"
            echo "==============================================="
            echo ""
            echo "Calculates and outputs predictive Semantic Versioning (SemVer) metadata"
            echo "based on Git commits and release tags, writing the result to 'VERSION'."
            echo ""
            echo "Usage:"
            echo "  $0 version"
            echo ""
            echo "How it works:"
            echo "  1. Baseline Discovery:"
            echo "     - Scans Git history for the most recent valid SemVer tag (e.g. v1.2.0 or 1.2.0)."
            echo "     - If no tag exists, uses DEFAULT_BASE_VERSION (default: 0.0.1)."
            echo ""
            echo "  2. Commit Inspection (range: <last_tag>..HEAD):"
            echo "     - Evaluates all commit messages following Conventional Commits format:"
            echo "       * MAJOR bump (X+1.0.0): Triggered by breaking change indicators:"
            echo "         - 'BREAKING CHANGE:' or 'BREAKING-CHANGE:' in commit body/footer"
            echo "         - '!' before colon in header (e.g. 'feat!:', 'fix(api)!:')"
            echo "       * MINOR bump (X.Y+1.0): Triggered by feature commits ('feat:' or 'feat(...):')"
            echo "       * PATCH bump (X.Y.Z+1): Triggered by any other conventional commit"
            echo "         (e.g. 'fix:', 'perf:', 'refactor:', 'docs:', 'chore:', etc.)"
            echo ""
            echo "  3. Output Format (in VERSION file):"
            echo "     - Clean release (commit is on a tag with 0 new commits):"
            echo "       <major>.<minor>.<patch> (e.g. 1.2.0)"
            echo "     - Development build (has new commits since last tag):"
            echo "       <target_version>-dev.<commit_count>+<YYYYMMDD>.<short_commit_hash>"
            echo "       Example: 1.3.0-dev.4+20260914.7a3c2b1"
            echo ""
            echo "Related commands:"
            echo "  $0 tag          - Create an annotated Git tag using the predicted version"
            echo "  $0 changelog    - Generate CHANGELOG.md based on conventional commits"
            ;;
        "tag")
            echo "cccp.sh tag - Create Release Tag & Synchronize Version/Changelog"
            echo "================================================================"
            echo ""
            echo "Creates an annotated Git tag, writes the clean version into 'VERSION',"
            echo "and regenerates 'CHANGELOG.md' to reflect the new release."
            echo ""
            echo "Usage:"
            echo "  $0 tag [version] [options]"
            echo ""
            echo "Arguments:"
            echo "  [version]         Target version. Optional. If omitted, uses the"
            echo "                    predictive SemVer version calculated from commits."
            echo "                    Flexible formats accepted:"
            echo "                      2       -> normalized to v2.0.0"
            echo "                      2.1     -> normalized to v2.1.0"
            echo "                      2.1.3   -> normalized to v2.1.3"
            echo "                      v2.1.3  -> normalized to v2.1.3"
            echo ""
            echo "Options:"
            echo "  --no-v            Create tag without 'v' prefix (e.g. 2.1.0 instead of v2.1.0)"
            echo "  -m, --message     Custom tag annotation message (default: 'Release <tag>')"
            echo "  -h, --help        Show this help message"
            echo ""
            echo "Actions performed:"
            echo "  1. Ensures working directory is clean (no uncommitted changes)."
            echo "  2. Verifies the tag does not already exist."
            echo "  3. Updates VERSION file with clean SemVer version (e.g. 2.1.0)."
            echo "  4. Regenerates CHANGELOG.md including the new release section."
            echo "  5. Creates release commit 'chore(release): <tag>' containing VERSION & CHANGELOG.md."
            echo "  6. Creates annotated Git tag pointing directly to the release commit."
            echo ""
            echo "Examples:"
            echo "  $0 tag                     # Automatically tag with predicted version (e.g. v0.3.0)"
            echo "  $0 tag 2                   # Creates tag v2.0.0"
            echo "  $0 tag 2.1                 # Creates tag v2.1.0"
            echo "  $0 tag 2.1.0               # Creates tag v2.1.0"
            echo "  $0 tag 2.1.0 --no-v        # Creates tag 2.1.0 (without 'v')"
            echo "  $0 tag 1.0.0 -m 'First GA' # Creates tag with custom annotation"
            ;;
        "commit")
            echo "cccp.sh commit - Conventional Commit Creation"
            echo "============================================="
            echo ""
            echo "Validates and creates a Git commit following the Conventional Commits specification."
            echo ""
            echo "Usage:"
            echo "  $0 commit <message>"
            echo ""
            echo "Format:"
            echo "  <type>(<scope>): <subject>"
            echo "  <type>(<scope>/<subscope>): <subject>"
            echo "  <type>!: <subject>  (Breaking Change)"
            echo ""
            echo "Types:"
            echo "  feat     - New feature"
            echo "  fix      - Bug fix"
            echo "  perf     - Performance improvement"
            echo "  refactor - Code refactoring"
            echo "  revert   - Revert changes"
            echo "  chore    - Maintenance tasks"
            echo "  build    - Build system changes"
            echo "  ci       - CI configuration changes"
            echo "  docs     - Documentation changes"
            echo "  ops      - Operational changes"
            echo "  style    - Code style changes"
            echo "  test     - Test related changes"
            echo "  merge    - Merge commits"
            echo ""
            echo "Examples:"
            echo "  $0 commit 'feat(ui): add dark mode switch'"
            echo "  $0 commit 'fix(api/auth): handle expired tokens'"
            echo "  $0 commit 'feat(core)!: drop support for legacy protocols'"
            ;;
        "changelog")
            echo "cccp.sh changelog - Conventional Changelog Generation"
            echo "===================================================="
            echo ""
            echo "Parses conventional commits in the Git history and generates or updates CHANGELOG.md."
            echo ""
            echo "Usage:"
            echo "  $0 changelog"
            echo ""
            echo "How it works:"
            echo "  1. Groups unreleased commits under '## [Unreleased]'."
            echo "  2. Groups commits between tags under each '### [<tag>]' release header."
            echo "  3. Categorizes commits into:"
            echo "     - Features (feat)"
            echo "     - Bug Fixes (fix)"
            echo "     - Performance Improvements (perf)"
            ;;
        "install")
            echo "cccp.sh install - Install Git Hooks"
            echo "==================================="
            echo ""
            echo "Installs Git hooks in '.git/hooks' to automate validation and release metadata:"
            echo ""
            echo "Usage:"
            echo "  $0 install"
            echo ""
            echo "Hooks installed:"
            echo "  - commit-msg:  Validates commit message format against Conventional Commits."
            echo "  - post-commit: Automatically runs 'changelog' and 'version' after each commit."
            ;;
        "update")
            echo "cccp.sh update - Update Script"
            echo "=============================="
            echo ""
            echo "Downloads and replaces the current cccp.sh script with the latest version"
            echo "from the upstream GitHub repository."
            echo ""
            echo "Usage:"
            echo "  $0 update"
            ;;
        "config")
            echo "cccp.sh config - Manage Hierarchical Configuration"
            echo "=================================================="
            echo ""
            echo "Inspect and modify global and repository-level configuration settings."
            echo ""
            echo "Precedence:"
            echo "  Defaults < Global (~/.config/cccp/config) < Local (.cccprc) < Environment < CLI flags"
            echo ""
            echo "Usage:"
            echo "  $0 config [--global|--local] <key> [value]"
            echo "  $0 config [--global|--local] --list"
            echo "  $0 config [--global|--local] --unset <key>"
            echo ""
            echo "Options:"
            echo "  --global, -g     Target global config file (~/.config/cccp/config)"
            echo "  --local          Target local repo config file (.cccprc)"
            echo "  --list, -l       List configuration key/value pairs"
            echo "  --unset          Remove a configuration key"
            echo "  -h, --help       Show this help message"
            echo ""
            echo "Supported Keys:"
            echo "  strict_scopes            Require scope to match known list (0 or 1, default: 0)"
            echo "  strict_subscopes         Require subscope to match known list (0 or 1, default: 0)"
            echo "  disable_subscopes        Disallow slash-delimited subscopes (0 or 1, default: 0)"
            echo "  disable_multiple_scopes  Disallow comma-separated scopes (0 or 1, default: 0)"
            echo "  default_base_version     Fallback SemVer when no tags exist (default: 0.0.1)"
            echo "  no_v                     Tag without 'v' prefix (0 or 1, default: 0)"
            echo "  update_channel           Update channel ('stable' or 'nightly', default: stable)"
            echo "  update_interval_days     Days between update checks (default: 30)"
            echo "  check_updates            Enable update checks (0 or 1, default: 1)"
            echo ""
            echo "Examples:"
            echo "  $0 config strict_scopes 1"
            echo "  $0 config --global update_channel nightly"
            echo "  $0 config default_base_version"
            echo "  $0 config --list"
            echo "  $0 config --unset strict_scopes"
            ;;
        *)
            echo "Git Conventional Commits Helper Script"
            echo "====================================="
            echo ""
            echo "This script provides tools for managing git commits following conventional commit"
            echo "standards, version management, and changelog generation."
            echo ""
            echo "Usage:"
            echo "  $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  commit <message>    Create a commit with a conventional commit message"
            echo "  install            Install git hooks for commit message validation"
            echo "  config             Manage global or repository configuration"
            echo "  version            Generate version information file"
            echo "  tag [version]      Create release tag, update VERSION and CHANGELOG"
            echo "  changelog          Generate or update CHANGELOG.md"
            echo "  update             Update the script to the latest version"
            echo "  help [command]     Show this help message or deep help on a command"
            echo ""
            echo "Git Hooks:"
            echo "  commit-msg         Validates commit messages for conventional commit format"
            echo "  post-commit        Automatically updates changelog and version after commit"
            echo ""
            echo "Commit Message Format:"
            echo "  <type>(<scope>): <subject>"
            echo ""
            echo "Types:"
            echo "  feat     - New feature"
            echo "  fix      - Bug fix"
            echo "  perf     - Performance improvement"
            echo "  refactor - Code refactoring"
            echo "  revert   - Revert changes"
            echo "  chore    - Maintenance tasks"
            echo "  build    - Build system changes"
            echo "  ci       - CI configuration changes"
            echo "  docs     - Documentation changes"
            echo "  ops      - Operational changes"
            echo "  style    - Code style changes"
            echo "  test     - Test related changes"
            echo "  merge    - Merge commits"
            echo ""
            echo "Scopes:"
            echo "  ui       - User interface changes"
            echo "  docs     - Documentation changes"
            echo "  api      - API changes"
            echo "  docker   - Docker related changes"
            echo "  db       - Database changes"
            echo ""
            echo "Subscopes:"
            echo "  components - UI components"
            echo "  pages      - Page components"
            echo "  services   - Service layer"
            echo "  utils      - Utility functions"
            echo "  auth       - Authentication related"
            echo "Environment Variables:"
            echo "  (All behavior flags default to 0 for inert/standard behavior)"
            echo "  STRICT_SCOPES             - Set to 1 to enforce only listed scopes (legacy: ALLOW_ANY_SCOPE=0)"
            echo "  STRICT_SUBSCOPES          - Set to 1 to enforce only listed subscopes (legacy: ALLOW_ANY_SUBSCOPE=0)"
            echo "  DISABLE_SUBSCOPES         - Set to 1 to disable subscopes"
            echo "  DISABLE_MULTIPLE_SCOPES   - Set to 1 to disable multiple scopes"
            echo "  DEFAULT_BASE_VERSION      - Fallback base version when no tags exist (default: 0.0.1)"
            echo ""
            echo "Examples:"
            echo "  $0 commit 'feat(ui): add new button'"
            echo "  $0 commit 'fix(api/auth): resolve login issue'"
            echo "  $0 install"
            echo "  $0 version"
            echo "  $0 tag 2.1.0"
            echo "  $0 changelog"
            echo "  $0 update"
            echo "  $0 help version"
            echo ""
            echo "Note: After installation, git hooks will automatically validate commit messages"
            echo "and update the changelog and version information after each commit."
            echo ""
            echo "For in-depth help on any command, run:"
            echo "  $0 help <command> (e.g. $0 help version, $0 help tag)"
            ;;
    esac
}