#!/bin/sh

# Enable error handling
set -eu

# =============================================================================
# Help Functions
# =============================================================================
# -----------------------------------------------------------------------------
# Display help information
# -----------------------------------------------------------------------------
show_help() {
    echo "Git Conventional Commits Helper Script"
    echo "====================================="
    echo ""
    echo "This script provides tools for managing git commits following conventional commit"
    echo "standards, version management, and changelog generation."
    echo ""
    echo "Usage:"
    echo "  $0 [command] [options]"
    echo ""
    echo "Commands:"
    echo "  commit <message>    Create a commit with a conventional commit message"
    echo "  install            Install git hooks for commit message validation"
    echo "  version            Generate version information file"
    echo "  changelog          Generate or update CHANGELOG.md"
    echo "  help               Show this help message"
    echo ""
    echo "Git Hooks:"
    echo "  commit-msg         Validates commit messages for conventional commit format"
    echo "  post-commit        Automatically updates changelog and version after commit"
    echo ""
    echo "Commit Message Format:"
    echo "  <type>(<scope>): <subject>"
    echo ""
    echo "Types:"
    echo "  feat     - New feature"
    echo "  fix      - Bug fix"
    echo "  perf     - Performance improvement"
    echo "  refactor - Code refactoring"
    echo "  revert   - Revert changes"
    echo "  chore    - Maintenance tasks"
    echo "  build    - Build system changes"
    echo "  ci       - CI configuration changes"
    echo "  docs     - Documentation changes"
    echo "  ops      - Operational changes"
    echo "  style    - Code style changes"
    echo "  test     - Test related changes"
    echo "  merge    - Merge commits"
    echo ""
    echo "Scopes:"
    echo "  ui       - User interface changes"
    echo "  docs     - Documentation changes"
    echo "  api      - API changes"
    echo "  docker   - Docker related changes"
    echo "  db       - Database changes"
    echo ""
    echo "Subscopes:"
    echo "  components - UI components"
    echo "  pages      - Page components"
    echo "  services   - Service layer"
    echo "  utils      - Utility functions"
    echo "  auth       - Authentication related"
    echo ""
    echo "Environment Variables:"
    echo "  DISABLE_SUBSCOPES         - Set to 1 to disable subscopes"
    echo "  DISABLE_MULTIPLE_SCOPES   - Set to 1 to disable multiple scopes"
    echo "  ALLOW_ANY_SUBSCOPE        - Set to 1 to allow any subscope"
    echo "  ALLOW_ANY_SCOPE           - Set to 1 to allow any scope"
    echo ""
    echo "Examples:"
    echo "  $0 commit 'feat(ui): add new button'"
    echo "  $0 commit 'fix(api/auth): resolve login issue'"
    echo "  $0 install"
    echo "  $0 version"
    echo "  $0 changelog"
    echo ""
    echo "Note: After installation, git hooks will automatically validate commit messages"
    echo "and update the changelog and version information after each commit."
} 